### ISSUE TITLE
Monaco editor support

### ISSUE THREAD

**Issue by dwilt** [hmarr/vscode-cel#1]
@hmarr Hello! Thanks so much for creating this plugin for VSCode. I know VSCode runs off Monaco under the hood and I'm looking to add CEL support to the Monaco editor.. 

I see you have the [`cel.tmlLangage.json` file](https://github.com/hmarr/vscode-cel/blob/main/syntaxes/cel.tmLanguage.json) which seems to define all the syntax for CEL. I'm kind of surprised though that it's not using `monaco.languages.register` and instead is just this JSON file.. can you shed any more light on that or how I could go about taking what you have here and applying it to Monaco directly?

**Comment by hmarr** [comment]
I gather Monaco doesn't support tmLanguage definitions, as they're reliant on a specific regex engine, which is written in C so can't be easily loaded on the web. I know some people have tried compiling the library to WebAssembly, so you could investigate that. Alternatively you could convert the tmLanguage definition to Monarch (the format Monaco uses). I asked ChatGPT to do the translation and it gave some plausible looking output, but I haven't tested it :-)
